// Generated by gencpp from file drempower/enable_msg.msg
// DO NOT EDIT!


#ifndef DREMPOWER_MESSAGE_ENABLE_MSG_H
#define DREMPOWER_MESSAGE_ENABLE_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drempower
{
template <class ContainerAllocator>
struct enable_msg_
{
  typedef enable_msg_<ContainerAllocator> Type;

  enable_msg_()
    : id(0)
    , cmd_mode(0)  {
    }
  enable_msg_(const ContainerAllocator& _alloc)
    : id(0)
    , cmd_mode(0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef uint8_t _cmd_mode_type;
  _cmd_mode_type cmd_mode;





  typedef boost::shared_ptr< ::drempower::enable_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drempower::enable_msg_<ContainerAllocator> const> ConstPtr;

}; // struct enable_msg_

typedef ::drempower::enable_msg_<std::allocator<void> > enable_msg;

typedef boost::shared_ptr< ::drempower::enable_msg > enable_msgPtr;
typedef boost::shared_ptr< ::drempower::enable_msg const> enable_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drempower::enable_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drempower::enable_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drempower::enable_msg_<ContainerAllocator1> & lhs, const ::drempower::enable_msg_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.cmd_mode == rhs.cmd_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drempower::enable_msg_<ContainerAllocator1> & lhs, const ::drempower::enable_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drempower

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::drempower::enable_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drempower::enable_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drempower::enable_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drempower::enable_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drempower::enable_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drempower::enable_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drempower::enable_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1052ee68e918215aa757f20d4ef4b17f";
  }

  static const char* value(const ::drempower::enable_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1052ee68e918215aULL;
  static const uint64_t static_value2 = 0xa757f20d4ef4b17fULL;
};

template<class ContainerAllocator>
struct DataType< ::drempower::enable_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drempower/enable_msg";
  }

  static const char* value(const ::drempower::enable_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drempower::enable_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
"uint8 cmd_mode\n"
"\n"
"\n"
;
  }

  static const char* value(const ::drempower::enable_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drempower::enable_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.cmd_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct enable_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drempower::enable_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drempower::enable_msg_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "cmd_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cmd_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DREMPOWER_MESSAGE_ENABLE_MSG_H
