// Generated by gencpp from file drempower/ip_msg.msg
// DO NOT EDIT!


#ifndef DREMPOWER_MESSAGE_IP_MSG_H
#define DREMPOWER_MESSAGE_IP_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drempower
{
template <class ContainerAllocator>
struct ip_msg_
{
  typedef ip_msg_<ContainerAllocator> Type;

  ip_msg_()
    : id(0)
    , cmd_mode(0)
    , torque(0.0)
    , Pos(0.0)
    , speed(0.0)
    , kp(0.0)
    , kd(0.0)  {
    }
  ip_msg_(const ContainerAllocator& _alloc)
    : id(0)
    , cmd_mode(0)
    , torque(0.0)
    , Pos(0.0)
    , speed(0.0)
    , kp(0.0)
    , kd(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef uint8_t _cmd_mode_type;
  _cmd_mode_type cmd_mode;

   typedef float _torque_type;
  _torque_type torque;

   typedef float _Pos_type;
  _Pos_type Pos;

   typedef float _speed_type;
  _speed_type speed;

   typedef float _kp_type;
  _kp_type kp;

   typedef float _kd_type;
  _kd_type kd;





  typedef boost::shared_ptr< ::drempower::ip_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drempower::ip_msg_<ContainerAllocator> const> ConstPtr;

}; // struct ip_msg_

typedef ::drempower::ip_msg_<std::allocator<void> > ip_msg;

typedef boost::shared_ptr< ::drempower::ip_msg > ip_msgPtr;
typedef boost::shared_ptr< ::drempower::ip_msg const> ip_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drempower::ip_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drempower::ip_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drempower::ip_msg_<ContainerAllocator1> & lhs, const ::drempower::ip_msg_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.cmd_mode == rhs.cmd_mode &&
    lhs.torque == rhs.torque &&
    lhs.Pos == rhs.Pos &&
    lhs.speed == rhs.speed &&
    lhs.kp == rhs.kp &&
    lhs.kd == rhs.kd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drempower::ip_msg_<ContainerAllocator1> & lhs, const ::drempower::ip_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drempower

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::drempower::ip_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drempower::ip_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drempower::ip_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drempower::ip_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drempower::ip_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drempower::ip_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drempower::ip_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d3fd0cf5bc3255fd077802cc1d02666";
  }

  static const char* value(const ::drempower::ip_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d3fd0cf5bc3255fULL;
  static const uint64_t static_value2 = 0xd077802cc1d02666ULL;
};

template<class ContainerAllocator>
struct DataType< ::drempower::ip_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drempower/ip_msg";
  }

  static const char* value(const ::drempower::ip_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drempower::ip_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
"uint8 cmd_mode\n"
"float32 torque \n"
"float32 Pos \n"
"float32 speed \n"
"float32 kp \n"
"float32 kd \n"
;
  }

  static const char* value(const ::drempower::ip_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drempower::ip_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.cmd_mode);
      stream.next(m.torque);
      stream.next(m.Pos);
      stream.next(m.speed);
      stream.next(m.kp);
      stream.next(m.kd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ip_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drempower::ip_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drempower::ip_msg_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "cmd_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cmd_mode);
    s << indent << "torque: ";
    Printer<float>::stream(s, indent + "  ", v.torque);
    s << indent << "Pos: ";
    Printer<float>::stream(s, indent + "  ", v.Pos);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "kp: ";
    Printer<float>::stream(s, indent + "  ", v.kp);
    s << indent << "kd: ";
    Printer<float>::stream(s, indent + "  ", v.kd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DREMPOWER_MESSAGE_IP_MSG_H
