// Generated by gencpp from file drempower/Target_point.msg
// DO NOT EDIT!


#ifndef DREMPOWER_MESSAGE_TARGET_POINT_H
#define DREMPOWER_MESSAGE_TARGET_POINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drempower
{
template <class ContainerAllocator>
struct Target_point_
{
  typedef Target_point_<ContainerAllocator> Type;

  Target_point_()
    : x(0.0)
    , y(0.0)
    , motion(false)  {
    }
  Target_point_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , motion(false)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef uint8_t _motion_type;
  _motion_type motion;





  typedef boost::shared_ptr< ::drempower::Target_point_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drempower::Target_point_<ContainerAllocator> const> ConstPtr;

}; // struct Target_point_

typedef ::drempower::Target_point_<std::allocator<void> > Target_point;

typedef boost::shared_ptr< ::drempower::Target_point > Target_pointPtr;
typedef boost::shared_ptr< ::drempower::Target_point const> Target_pointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drempower::Target_point_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drempower::Target_point_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::drempower::Target_point_<ContainerAllocator1> & lhs, const ::drempower::Target_point_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.motion == rhs.motion;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::drempower::Target_point_<ContainerAllocator1> & lhs, const ::drempower::Target_point_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace drempower

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::drempower::Target_point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drempower::Target_point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drempower::Target_point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drempower::Target_point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drempower::Target_point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drempower::Target_point_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drempower::Target_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "943eefa7a7b753a3f2176e70f130d3b3";
  }

  static const char* value(const ::drempower::Target_point_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x943eefa7a7b753a3ULL;
  static const uint64_t static_value2 = 0xf2176e70f130d3b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::drempower::Target_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drempower/Target_point";
  }

  static const char* value(const ::drempower::Target_point_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drempower::Target_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"bool motion\n"
;
  }

  static const char* value(const ::drempower::Target_point_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drempower::Target_point_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.motion);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Target_point_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drempower::Target_point_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drempower::Target_point_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "motion: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.motion);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DREMPOWER_MESSAGE_TARGET_POINT_H
