# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from drempower/property_msg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class property_msg(genpy.Message):
  _md5sum = "c56a37b89789465bc1a39487c8492c4f"
  _type = "drempower/property_msg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 id
uint8 cmd_mode
uint16 cmd_data
uint16 address
uint16 data_type
float32 value"""
  __slots__ = ['id','cmd_mode','cmd_data','address','data_type','value']
  _slot_types = ['uint8','uint8','uint16','uint16','uint16','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,cmd_mode,cmd_data,address,data_type,value

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(property_msg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.cmd_mode is None:
        self.cmd_mode = 0
      if self.cmd_data is None:
        self.cmd_data = 0
      if self.address is None:
        self.address = 0
      if self.data_type is None:
        self.data_type = 0
      if self.value is None:
        self.value = 0.
    else:
      self.id = 0
      self.cmd_mode = 0
      self.cmd_data = 0
      self.address = 0
      self.data_type = 0
      self.value = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2B3Hf().pack(_x.id, _x.cmd_mode, _x.cmd_data, _x.address, _x.data_type, _x.value))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.id, _x.cmd_mode, _x.cmd_data, _x.address, _x.data_type, _x.value,) = _get_struct_2B3Hf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2B3Hf().pack(_x.id, _x.cmd_mode, _x.cmd_data, _x.address, _x.data_type, _x.value))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.id, _x.cmd_mode, _x.cmd_data, _x.address, _x.data_type, _x.value,) = _get_struct_2B3Hf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B3Hf = None
def _get_struct_2B3Hf():
    global _struct_2B3Hf
    if _struct_2B3Hf is None:
        _struct_2B3Hf = struct.Struct("<2B3Hf")
    return _struct_2B3Hf
