# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from drempower/state_msg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class state_msg(genpy.Message):
  _md5sum = "7e078fbada3d91b85209b327d5ded4f9"
  _type = "drempower/state_msg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint16 id
uint8 cmd_mode
uint16 cmd_data
float32 pos_estimate
float32 vel_estimate
float32  torque_estimate
float32 temp"""
  __slots__ = ['id','cmd_mode','cmd_data','pos_estimate','vel_estimate','torque_estimate','temp']
  _slot_types = ['uint16','uint8','uint16','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,cmd_mode,cmd_data,pos_estimate,vel_estimate,torque_estimate,temp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(state_msg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.cmd_mode is None:
        self.cmd_mode = 0
      if self.cmd_data is None:
        self.cmd_data = 0
      if self.pos_estimate is None:
        self.pos_estimate = 0.
      if self.vel_estimate is None:
        self.vel_estimate = 0.
      if self.torque_estimate is None:
        self.torque_estimate = 0.
      if self.temp is None:
        self.temp = 0.
    else:
      self.id = 0
      self.cmd_mode = 0
      self.cmd_data = 0
      self.pos_estimate = 0.
      self.vel_estimate = 0.
      self.torque_estimate = 0.
      self.temp = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_HBH4f().pack(_x.id, _x.cmd_mode, _x.cmd_data, _x.pos_estimate, _x.vel_estimate, _x.torque_estimate, _x.temp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 21
      (_x.id, _x.cmd_mode, _x.cmd_data, _x.pos_estimate, _x.vel_estimate, _x.torque_estimate, _x.temp,) = _get_struct_HBH4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_HBH4f().pack(_x.id, _x.cmd_mode, _x.cmd_data, _x.pos_estimate, _x.vel_estimate, _x.torque_estimate, _x.temp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 21
      (_x.id, _x.cmd_mode, _x.cmd_data, _x.pos_estimate, _x.vel_estimate, _x.torque_estimate, _x.temp,) = _get_struct_HBH4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_HBH4f = None
def _get_struct_HBH4f():
    global _struct_HBH4f
    if _struct_HBH4f is None:
        _struct_HBH4f = struct.Struct("<HBH4f")
    return _struct_HBH4f
